# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Thoughts_BlogApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Thoughts_BlogApp

   pod 'Firebase/Core'
   pod 'Firebase/Storage'
   pod 'Firebase/Firestore'
   pod 'Firebase/Auth'
   pod 'Purchases' 

pod 'ProgressHUD'

pod 'RxSwift'
pod 'RxCocoa' 

pod 'FirebaseFirestoreSwift', '> 7.0-beta'


end
